/* Phone Game Lab — game catalog (used by launcher) */
window.LAB_GAMES = [
  { cat:"Reflex & Taps", items:[
    {n:1,  slug:"01-tap-frenzy",     t:"Tap Frenzy",        d:"Tap as many circles as you can before time runs out."},
    {n:2,  slug:"02-whack-a-mole",   t:"Whack-a-Mole",      d:"Whack moles that pop up — avoid the bombs."},
    {n:3,  slug:"03-reaction-duel",  t:"Reaction Duel",     d:"Wait for the signal — fastest finger wins."},
    {n:4,  slug:"04-quick-draw",     t:"Quick Draw",        d:"Cowboy duel: don't fire before \"DRAW!\"."},
    {n:5,  slug:"05-find-difference",t:"Find the Difference",d:"Spot the cell that's different from the rest."},
    {n:6,  slug:"06-odd-one-out",    t:"Odd One Out",       d:"Tap the face whose expression differs."},
    {n:7,  slug:"07-memory-match",   t:"Memory Match",      d:"Flip cards and find matching pairs."},
    {n:8,  slug:"08-shell-game",     t:"Cups & Ball",       d:"Watch the cups shuffle. Where's the ball?"},
  ]},
  { cat:"Arcade & Action", items:[
    {n:9,  slug:"09-brick-breaker",  t:"Brick Breaker",     d:"Paddle a ball to destroy the wall."},
    {n:10, slug:"10-bubble-shooter", t:"Bubble Shooter",    d:"Match 3+ bubbles of the same color."},
    {n:11, slug:"11-space-invaders", t:"Space Invaders",    d:"Shoot the descending alien grid."},
    {n:12, slug:"12-asteroids",      t:"Asteroids",         d:"Rotate, thrust, and shoot the rocks."},
    {n:13, slug:"13-twin-stick",     t:"Twin-Stick Arena",  d:"Two thumbs: one moves, one shoots."},
    {n:14, slug:"14-bullet-hell",    t:"Bullet Hell",       d:"Survive dense bullet patterns."},
    {n:15, slug:"15-fruit-slice",    t:"Fruit Slice",       d:"Swipe to slice fruit, dodge bombs."},
    {n:16, slug:"16-knife-throw",    t:"Knife Throw",       d:"Stick knives in a spinning log."},
    {n:17, slug:"17-bow-arrow",      t:"Bow & Arrow",       d:"Drag to aim, release to fire."},
    {n:18, slug:"18-sniper-timing",  t:"Sniper Timing",     d:"One shot — wait for the perfect moment."},
    {n:19, slug:"19-cannon",         t:"Cannon",            d:"Lob projectiles in a parabola."},
  ]},
  { cat:"Runner & Movement", items:[
    {n:20, slug:"20-endless-runner", t:"Endless Runner",    d:"Tap to jump, swipe down to slide."},
    {n:21, slug:"21-lane-dodger",    t:"Lane Dodger",       d:"Swipe between 3 lanes to dodge."},
    {n:22, slug:"22-traffic-dodge",  t:"Traffic Dodge",     d:"Top-down: weave through traffic."},
    {n:23, slug:"23-doodle-jump",    t:"Doodle Jump",       d:"Auto-bounce upward, tilt to steer."},
    {n:24, slug:"24-helix-fall",     t:"Helix Fall",        d:"Rotate the tower so the ball falls through gaps."},
    {n:25, slug:"25-stair-climb",    t:"Stair Climb",       d:"Tap left/right to climb stairs — don't slip."},
    {n:26, slug:"26-flappy",         t:"Flappy Tap",        d:"Tap to flap through pipe gaps."},
    {n:27, slug:"27-jetpack",        t:"Jetpack Hold",      d:"Hold to fly, release to fall."},
    {n:28, slug:"28-cave-flyer",     t:"Cave Flyer",        d:"Navigate a narrowing cave tunnel."},
    {n:29, slug:"29-marble-maze",    t:"Marble Maze",       d:"Drag the marble through walls to the goal."},
    {n:30, slug:"30-balance-beam",   t:"Balance Beam",      d:"Tap left/right to keep your balance."},
    {n:31, slug:"31-disappearing-tiles", t:"Vanishing Tiles", d:"Stand only on tiles that aren't fading."},
    {n:32, slug:"32-color-path",     t:"Color Path",        d:"Tap to switch color — only step on matching tiles."},
    {n:33, slug:"33-shape-gate",     t:"Shape Gate",        d:"Morph shape to fit the gate's hole."},
    {n:34, slug:"34-stack-runner",   t:"Stack Runner",      d:"Collect blocks, lay them to cross gaps."},
  ]},
  { cat:"Stack & Physics", items:[
    {n:35, slug:"35-cake-tower",     t:"Cake Tower",        d:"Drop swinging layers — perfect timing."},
    {n:36, slug:"36-sky-high",       t:"Sky High Stack",    d:"Sliding blocks, only matching overlap stays."},
    {n:37, slug:"37-suika-merge",    t:"Suika Merge",       d:"Drop fruit, merge equals into bigger fruit."},
    {n:38, slug:"38-plinko",         t:"Plinko",            d:"Drop the ball — chase the big multiplier."},
    {n:39, slug:"39-basketball",     t:"Basketball Flick",  d:"Flick to shoot, arc to the hoop."},
    {n:40, slug:"40-pool",           t:"Pool",              d:"Drag-aim the cue, pot the balls."},
    {n:41, slug:"41-goal-flick",     t:"Goal! Flick",       d:"Flick the ball past the keeper."},
    {n:42, slug:"42-bridge-build",   t:"Bridge Build",      d:"Hold to extend a bridge over the gap."},
  ]},
  { cat:"Puzzle & Logic", items:[
    {n:43, slug:"43-2048",           t:"2048",              d:"Swipe to merge equal tiles."},
    {n:44, slug:"44-match-3",        t:"Match-3 Swap",      d:"Swap adjacent gems to make 3+ in a row."},
    {n:45, slug:"45-tap-clusters",   t:"Tap Clusters",      d:"Tap groups of same-color blocks to pop them."},
    {n:46, slug:"46-connect-dots",   t:"Connect Dots",      d:"Draw lines between pairs — no crossings."},
    {n:47, slug:"47-pipe-rotate",    t:"Pipe Connect",      d:"Rotate pipes so water reaches the end."},
    {n:48, slug:"48-water-sort",     t:"Water Sort",        d:"Pour colors between tubes until each is one color."},
    {n:49, slug:"49-ball-sort",      t:"Ball Sort",         d:"Move balls between tubes to sort by color."},
    {n:50, slug:"50-screw-puzzle",   t:"Screw Puzzle",      d:"Unscrew bolts in the right order to free parts."},
    {n:51, slug:"51-15-puzzle",      t:"Sliding 15-Puzzle", d:"Slide numbered tiles into order."},
    {n:52, slug:"52-tetris",         t:"Tetris",            d:"Fit falling pieces, clear lines."},
    {n:53, slug:"53-block-blast",    t:"Block Blast",       d:"Place blocks to clear full rows/cols."},
    {n:54, slug:"54-maze",           t:"Maze",              d:"Find the path from start to goal."},
    {n:55, slug:"55-laser-mirror",   t:"Laser Mirror",      d:"Rotate mirrors to hit the target."},
    {n:56, slug:"56-lights-out",     t:"Lights Out",        d:"Toggle cells to turn off every light."},
    {n:57, slug:"57-minesweeper",    t:"Minesweeper",       d:"Use number hints to find safe cells."},
    {n:58, slug:"58-word-search",    t:"Word Search",       d:"Drag through the grid to find hidden words."},
    {n:59, slug:"59-nonogram",       t:"Nonogram",          d:"Use hints to fill the correct cells."},
    {n:60, slug:"60-sudoku",         t:"Sudoku Mini",       d:"Fill the 4×4 grid — no row/col/box repeats."},
  ]},
  { cat:".io & Idle", items:[
    {n:61, slug:"61-snake",          t:"Snake",             d:"Eat fruit — don't bite yourself."},
    {n:62, slug:"62-slither",        t:"Slither Grow",      d:"Eat dots, grow long, dodge the snake."},
    {n:63, slug:"63-agar",           t:"Agar Absorb",       d:"Eat smaller blobs, dodge bigger ones."},
    {n:64, slug:"64-tower-defense",  t:"Tower Defense",     d:"Place turrets to stop the waves."},
    {n:65, slug:"65-idle-clicker",   t:"Idle Clicker",      d:"Tap, buy upgrades, automate income."},
    {n:66, slug:"66-merge-idle",     t:"Merge Idle",        d:"Merge generators for compounding income."},
  ]},
  { cat:"Skill & Rhythm", items:[
    {n:67, slug:"67-cooking-serve",  t:"Cooking Serve",     d:"Drag the right ingredients to each order."},
    {n:68, slug:"68-sort-baskets",   t:"Sort Baskets",      d:"Fling falling items into the right basket."},
    {n:69, slug:"69-piano-tiles",    t:"Piano Tiles",       d:"Tap the black tiles — never miss one."},
    {n:70, slug:"70-rhythm-lane",    t:"Rhythm Lane",       d:"Hit notes in their lanes in time with the beat."},
  ]},
];
