/* Phone Game Lab 2 — game catalog (Talking Tom minigame prototypes) */
window.LAB_GAMES = [
  { cat:"A – B", items:[
    {n:1,  slug:"2048",                  t:"2048",                 d:"Swipe to merge equal tiles up to 2048."},
    {n:2,  slug:"balloon-splash",        t:"Balloon Splash",       d:"Throw water balloons at moving targets."},
    {n:3,  slug:"basketball",            t:"Basketball",           d:"Flick shots into the hoop against the clock."},
    {n:4,  slug:"berry-bounce",          t:"Berry Bounce",         d:"Bounce a berry off platforms into a basket."},
    {n:5,  slug:"brick-blast",           t:"Brick Blast",          d:"Tap groups of same-colored bricks to pop them."},
    {n:6,  slug:"brick-breaker",         t:"Brick Breaker",        d:"Paddle a ball to smash a wall of bricks."},
    {n:7,  slug:"bridge",                t:"Bridge",               d:"Hold to grow a bridge that exactly crosses the gap."},
    {n:8,  slug:"bubble-shooter",        t:"Bubble Shooter",       d:"Shoot bubbles to match 3+ and clear the board."},
    {n:9,  slug:"bubble-up",             t:"Bubble Up",            d:"Float upward in a bubble, dodging falling spikes."},
    {n:10, slug:"building-block-puzzle", t:"Block Puzzle",         d:"Place tetromino pieces and clear full lines."},
    {n:11, slug:"bumper-park",           t:"Bumper Park",          d:"Ram opponents off the arena in a bumper car."},
    {n:12, slug:"busy-bugs",             t:"Busy Bugs",            d:"Swipe bugs away before they reach the food."},
  ]},
  { cat:"C – D", items:[
    {n:13, slug:"cake-tower",            t:"Cake Tower",           d:"Drop swinging cake layers to build a balanced tower."},
    {n:14, slug:"candy-connect",         t:"Candy Connect",        d:"Draw a line through matching candies to clear them."},
    {n:15, slug:"castle-craft",          t:"Castle Craft",         d:"Sandbox: place blocks to build your toy castle."},
    {n:16, slug:"cats-and-cans",         t:"Cats & Cans",          d:"Classic shell game — track the cup hiding the cat."},
    {n:17, slug:"clean-the-ocean",       t:"Clean the Ocean",      d:"Drop a claw to grab trash and keep the ocean clean."},
    {n:18, slug:"climber-tom",           t:"Climber Tom",          d:"Climb a wall by jumping between sides; dodge spikes."},
    {n:19, slug:"connect",               t:"Connect",              d:"Draw paths to link same-colored dots without crossing."},
    {n:20, slug:"cupid-tom",             t:"Cupid Tom",            d:"Shoot arrows at flying hearts cupid-style."},
    {n:21, slug:"destroy-aliens",        t:"Destroy Aliens",       d:"Hold off waves of descending alien invaders."},
    {n:22, slug:"donut-spin",            t:"Donut Spin",           d:"Throw knives into a spinning donut without hitting them."},
    {n:23, slug:"dress-up",              t:"Dress Up",             d:"Drag hats, glasses and outfits onto the character."},
  ]},
  { cat:"F – G", items:[
    {n:24, slug:"face-designer",         t:"Face Designer",        d:"Paint face make-up on a character with your finger."},
    {n:25, slug:"find-pattern",          t:"Find Pattern",         d:"Watch the sequence, then repeat it perfectly."},
    {n:26, slug:"fishtastic",            t:"Fishtastic",           d:"Swim through the sea and catch the requested fish."},
    {n:27, slug:"fishy-frenzy",          t:"Fishy Frenzy",         d:"Eat smaller fish to grow; flee the bigger ones."},
    {n:28, slug:"flappy-tom",            t:"Flappy Tom",           d:"Tap to flap through narrow gaps between pipes."},
    {n:29, slug:"football",              t:"Football",             d:"Swipe to shoot the ball past the goalkeeper."},
    {n:30, slug:"fruit-boom",            t:"Fruit Boom",           d:"Swipe to slice flying fruit, fruit-ninja style."},
    {n:31, slug:"go-up",                 t:"Go Up",                d:"Hop from a moving platform to the next to climb."},
    {n:32, slug:"goal",                  t:"Goal!",                d:"Precision shot — hit the target inside the goal."},
    {n:33, slug:"guitar-ace",            t:"Guitar Ace",           d:"Tap the falling notes in time with the rhythm."},
  ]},
  { cat:"H – I", items:[
    {n:34, slug:"happy-connect",         t:"Happy Connect",        d:"Draw lines to match identical happy faces."},
    {n:35, slug:"happy-face",            t:"Happy Face",           d:"Find the odd face out before time runs out."},
    {n:36, slug:"hit-the-road",          t:"Hit The Road",         d:"Switch lanes to dodge traffic and grab coins."},
    {n:37, slug:"hole-chase",            t:"Hole Chase",           d:"Move a black hole to swallow objects and grow."},
    {n:38, slug:"hungry-fish",           t:"Hungry Fish",          d:"Guide a hungry fish to its food, past hazards."},
    {n:39, slug:"ice-cream-shop",        t:"Ice Cream Shop",       d:"Serve the right ice cream to impatient customers."},
    {n:40, slug:"ice-smash",             t:"Ice Smash",            d:"Tap to shatter all the ice before moves run out."},
  ]},
  { cat:"J / M / P", items:[
    {n:41, slug:"jigsaw-puzzles",        t:"Jigsaw Puzzles",       d:"Drag scrambled pieces back into the picture."},
    {n:42, slug:"jump",                  t:"Jump",                 d:"Time your jumps between platforms to survive."},
    {n:43, slug:"jungle-shot",           t:"Jungle Shot",          d:"Slingshot projectiles at jungle targets."},
    {n:44, slug:"make-a-kite",           t:"Make a Kite",          d:"Decorate a kite, then fly it through the wind."},
    {n:45, slug:"marble-mix-up",         t:"Marble Mix Up",        d:"Shoot marbles into the line to match three (Zuma)."},
    {n:46, slug:"maze",                  t:"Maze",                 d:"Find the way out of the maze."},
    {n:47, slug:"memory",                t:"Memory",               d:"Flip cards two at a time and find the pairs."},
    {n:48, slug:"monkey-catch",          t:"Monkey Catch",         d:"Catch falling bananas; dodge bombs."},
    {n:49, slug:"mower",                 t:"Mower",                d:"Drive the mower so it covers every patch of grass."},
    {n:50, slug:"pinata-drop",           t:"Piñata Drop",          d:"Catch candy raining down from a smashed piñata."},
    {n:51, slug:"planet-hop",            t:"Planet Hop",           d:"Tap to leap from one spinning planet to the next."},
  ]},
  { cat:"R – S", items:[
    {n:52, slug:"race-car",              t:"Race Car",             d:"Top-down race: weave through opponents to the finish."},
    {n:53, slug:"rainbows",              t:"Rainbows",             d:"Connect dots with rainbow arcs across the screen."},
    {n:54, slug:"rocket-fun",            t:"Rocket Fun",           d:"Steer a rocket between asteroids in space."},
    {n:55, slug:"rolling-ball",          t:"Rolling Ball",         d:"Tilt-style: drag a ball through a tight maze."},
    {n:56, slug:"sky-high",              t:"Sky High",             d:"Drop sliding floors to build the tallest tower."},
    {n:57, slug:"sky-race",              t:"Sky Race",             d:"Race a hoverboard through the sky, dodging walls."},
    {n:58, slug:"sky-skater",            t:"Sky Skater",           d:"Skate over sky-borne gaps; nail the jump timing."},
    {n:59, slug:"sleepy-bugs",           t:"Sleepy Bugs",          d:"Logic puzzle: pair each bug with its matching bed."},
    {n:60, slug:"slice-and-sip",         t:"Slice and Sip",        d:"Slice fruit so it lands in the blender below."},
    {n:61, slug:"sliding-pets",          t:"Sliding Pets",         d:"Slide pets out of the way to free the hero."},
    {n:62, slug:"snack-baskets",         t:"Snack Baskets",        d:"Sort falling snacks into the matching baskets."},
    {n:63, slug:"snake-trails",          t:"Snake Trails",         d:"Slither.io-style: eat dots and grow, dodge rivals."},
    {n:64, slug:"snakes-and-ladders",    t:"Snakes & Ladders",     d:"Classic board game — roll the dice to the finish."},
    {n:65, slug:"snappy-frog",           t:"Snappy Frog",          d:"Aim the frog's tongue to snap up flying flies."},
    {n:66, slug:"space-piano",           t:"Space Piano",          d:"Tap the falling black tiles in rhythm."},
    {n:67, slug:"space-trails",          t:"Space Trails",         d:"Draw routes that get every ship to its target."},
    {n:68, slug:"splashy",               t:"Splashy",              d:"Time taps to splash from puddle to puddle."},
    {n:69, slug:"spooky-train",          t:"Spooky Train",         d:"Steer a train at junctions through a haunted land."},
    {n:70, slug:"spray-paint",           t:"Spray Paint",          d:"Spray-paint a stencil — stay inside the lines."},
    {n:71, slug:"sub-adventure",         t:"Sub Adventure",        d:"Pilot a sub through narrow undersea caves."},
    {n:72, slug:"super-balloons",        t:"Super Balloons",       d:"Pop the rising balloons as fast as you can."},
  ]},
  { cat:"T / U / W", items:[
    {n:73, slug:"tap-tap",               t:"Tap Tap",              d:"Pure reflex: tap the target enough times in time."},
    {n:74, slug:"tiny-puzzles",          t:"Tiny Puzzles",         d:"Rotate the tiles until the picture is whole."},
    {n:75, slug:"tom-run",               t:"Tom Run",              d:"Endless runner: swipe to jump, slide and dodge."},
    {n:76, slug:"totem-blast",           t:"Totem Blast",          d:"Tap matching totem groups before the tower rises out of view."},
    {n:77, slug:"unicorns",              t:"Unicorns",             d:"Fly a unicorn through floating rings."},
    {n:78, slug:"water-rush",            t:"Water Rush",           d:"Rotate pipes so water flows from source to sink."},
    {n:79, slug:"whack-a-mouse",         t:"Whack-A-Mouse",        d:"Whack mice; avoid hitting the mouse traps."},
    {n:80, slug:"wire-ball",             t:"Wire Ball",            d:"Drag a ring along a wire without touching it."},
  ]},
];
